[theme]
base = "dark"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#302b63"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false
